name: ampact
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^1.8.0
  firebase_auth: ^3.1.4
  cloud_firestore: ^3.1.6
  flutterfire_ui: ^0.3.1
  provider: ^6.0.1
  path_provider: ^2.0.8
  google_fonts: ^2.2.0
  tflite_flutter: ^0.9.0
  tflite_flutter_helper: ^0.3.1
  flutter_tts: ^3.3.3
  camera: ^0.9.4+5
  font_awesome_flutter: ^9.2.0
  persistent_bottom_nav_bar: ^4.0.2
  auto_size_text: ^3.0.0
  location: ^4.3.0
  url_launcher: ^6.0.18
  flutter_phone_direct_caller: ^2.1.0
  flutter_speed_dial: ^5.0.0+1
  animate_icons: ^2.0.0
  qr_flutter: ^4.0.0
  qr_code_scanner: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/model/
